### ISSUE TITLE
KeyError: 'cipher'

### ISSUE THREAD

**Issue by MuhammadAlzamily** [nficano/pytube#696]
So i have just found out about this library and was so excited to try it until i ran into few bugs i managed to take care of some but currently stuck with this one i'm going to paste in the full traceback to 

`Traceback (most recent call last):
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 297, in apply_descrambler
    for format_item in formats
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 297, in <listcomp>       
    for format_item in formats
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/Windows 10/Desktop/python/index.py", line 2, in <module>
    YouTube("https://www.youtube.com/watch?v=ciYFgVpya5k&list=LLsh1YkVitp9_cpdqlC2FSpQ&index=2&t=0s").streams.first().download()
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 92, in __init__
    self.descramble()
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 132, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 301, in apply_descrambler
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 301, in <listcomp>
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
KeyError: 'cipher'`

**Comment by MattiaDel** [comment]
You should change one line in "extract.py"

from:
`cipher_url = [
                parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
            ]`

to:
`cipher_url = [
                parse_qs(formats[i]["signatureCipher"]) for i, data in enumerate(formats)
            ]`

**Comment by ZippyDoodah123** [comment]
In future @MuhammadAlzamily please check before just posting the issue here. If you googled it you would have found the fix.

**Comment by RONNCC** [comment]
Closing issue -- feel free to follow up in #642 

Also would love a PR for this in case anyone has time (@ZippyDoodah123  @MattiaDel  @MuhammadAlzamily )
